version: '3.8'
services:
  backend-service:
    image: 'image-backend'
    container_name: 'container-backend'
    env_file:
      - ./.env
    ports:
      - 5000:5000

  client-service:
    image: 'image-frontend'
    container_name: 'container_frontend'
    env_file:
      - ./frontend/.env
    ports:
      - 3000:3000
