export const VERIFY_EMAIL_REQUEST = 'VERIFY_EMAIL_REQUEST';
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAIL = 'VERIFY_EMAIL_FAIL';
export const VERIFY_EMAIL_RESET = 'VERIFY_EMAIL_RESET';

export const GET_VERIFY_EMAIL_REQUEST = 'GET_VERIFY_EMAIL_REQUEST';
export const GET_VERIFY_EMAIL_SUCCESS = 'GET_VERIFY_EMAIL_SUCCESS';
export const GET_VERIFY_EMAIL_FAIL = 'GET_VERIFY_EMAIL_FAIL';
export const GET_VERIFY_EMAIL_RESET = 'GET_VERIFY_EMAIL_RESET';
